version: "2"
linters:
  enable:
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
formatters:
  enable:
    - gofumpt
