---
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cli/
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w'
      - -X github.com/drewstinnett/sourceseedy/cli/cmd.date={{ .CommitDate }}
      - -X github.com/drewstinnett/sourceseedy/cli/cmd.version={{ .Tag }}
      - -X github.com/drewstinnett/sourceseedy/cli/cmd.commit={{ .ShortCommit }}
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'sourceseedy'
archives:
  - formats:
      - tar.gz
    name_template: 'sourceseedy-{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
checksum:
  name_template: 'sourceseedy-{{ .Version }}_SHA256SUMS'
  algorithm: sha256
snapshot:
  version_template: "{{ .Tag }}-snapshot"
changelog:
  disable: true

brews:
  - name: 'sourceseedy'
    repository:
      owner: drewstinnett
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "Easily switch between source directories"
    homepage: "https://github.com/drewstinnett/sourceseedy"
    license: BSD-2-Clause
    caveats: |
      Add the following to your shell config to get the scd command, which
      fzf's your way in to a project:

        bash, zsh: eval "$(sourceseedy init zsh)"
        fish:      sourceseedy init fish | source
